# Generated by Django 5.1.1 on 2024-09-10 19:26

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idcategoria', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Categoría')),
                ('estado', models.BooleanField(blank=True, default=True, null=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['idcategoria'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('idmarca', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Marca')),
                ('estado', models.BooleanField(blank=True, default=True, null=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['idmarca'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código Cliente')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula')),
                ('telefono', models.CharField(max_length=20, unique=True, verbose_name='Teléfono')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('genero', models.CharField(blank=True, choices=[('1', 'Hombre'), ('2', 'Mujer')], default='1', max_length=1, verbose_name='Género')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['codigo', 'nombre', 'apellido'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('imagen', models.ImageField(blank=True, max_length=500, null=True, upload_to='producto', verbose_name='Imagen')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código Producto')),
                ('nombre', models.CharField(blank=True, max_length=100, verbose_name='Producto')),
                ('descripcion', models.TextField(blank=True, max_length=200, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Precio')),
                ('fecha_elaboracion', models.DateField(blank=True, default=datetime.datetime.today, null=True, verbose_name='Fecha Elaboración')),
                ('fecha_expiracion', models.DateField(blank=True, null=True, verbose_name='Fecha Expiración')),
                ('estado', models.BooleanField(blank=True, default=True, null=True, verbose_name='Estado')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='Super.categoria', verbose_name='Categoría')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='Super.marca', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['codigo', 'nombre', 'descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('idvendedor', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código Vendedor')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula')),
                ('telefono', models.CharField(max_length=20, unique=True, verbose_name='Teléfono')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('genero', models.CharField(blank=True, choices=[('1', 'Hombre'), ('2', 'Mujer')], default='1', max_length=1, verbose_name='Género')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'ordering': ['codigo', 'nombre', 'apellido'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idventa', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('fecha', models.DateField(blank=True, default=datetime.datetime.today, verbose_name='Fecha de Venta')),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Subtotal')),
                ('iva', models.DecimalField(blank=True, decimal_places=2, default=0.15, max_digits=10, verbose_name='Iva')),
                ('dscto', models.FloatField(blank=True, default=0.0, verbose_name='Descuento')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='Super.cliente', verbose_name='Cliente')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='Super.vendedor', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['idventa', 'fecha'],
            },
        ),
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('iddetalle', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('precio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Precio')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Subtotal')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='Super.producto', verbose_name='Producto')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='Super.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
                'ordering': ['iddetalle', 'venta'],
            },
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('precio__gte', 0)), name='ck_precio_positivo'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='check_subtotal_positivo'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.CheckConstraint(condition=models.Q(('iva__gte', 0)), name='check_iva_positivo'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.CheckConstraint(condition=models.Q(('dscto__gte', 0)), name='check_dscto_positivo'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='check_total_positivo'),
        ),
        migrations.AddConstraint(
            model_name='ventadetalle',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gte', 0)), name='check_cantidad_positivo'),
        ),
        migrations.AddConstraint(
            model_name='ventadetalle',
            constraint=models.CheckConstraint(condition=models.Q(('precio__gte', 0)), name='check_precio_positivo'),
        ),
        migrations.AddConstraint(
            model_name='ventadetalle',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='check_subtotal_detalle_positivo'),
        ),
    ]
